spring.application.name=Turismo

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.apffjlspwwjxwokjekcd
spring.datasource.password=Turism01233$!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=arequipa_tours_clave_secreta_super_segura_2024_aqpgo
jwt.expiration=86400000

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.session.store-type=none


####################################################
# ACTUATOR
####################################################

management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=always

management.info.env.enabled=true

management.endpoint.health.probes.enabled=true

management.prometheus.metrics.export.enabled=true

####################################################
# MICROMETER
####################################################

management.metrics.tags.application=AqpGo Backend
management.metrics.tags.environment=Render Free
management.metrics.tags.version=1.0.0


####################################################
# INFORMACIÓN DEL SISTEMA
####################################################

info.app.name=AqpGo Backend

info.app.version=1.0.0

info.app.description=Backend REST desarrollado con Spring Boot

info.app.author=Equipo AqpGo

####################################################
# SENTRY
####################################################

sentry.dsn=https://a322e3123aff90aabb2e1d06e0909def@o4511669536489472.ingest.us.sentry.io/4511669546385408

sentry.environment=development

sentry.release=aqpgo-backend@1.0.0

sentry.send-default-pii=true

sentry.traces-sample-rate=1.0

sentry.debug=true