spring.application.name=Turismo

spring.datasource.url=jdbc:postgresql://dpg-d7s0tfbt6lks73800o4g-a.oregon-postgres.render.com:5432/aqpgo
spring.datasource.username=aqpgo_user
spring.datasource.password=WE7rQisEUDIpz77uHCRGwo6pqb61wMFP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=arequipa_tours_clave_secreta_super_segura_2024_aqpgo
jwt.expiration=86400000

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.session.store-type=none