spring.application.name=Turismo

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.apffjlspwwjxwokjekcd
spring.datasource.password=Turism01233$!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=arequipa_tours_clave_secreta_super_segura_2024_aqpgo
jwt.expiration=86400000

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.session.store-type=none
